from __future__ import annotations

from typing import List

from backend.order_observation_schema import OrderObservation


def load_sample_observations() -> List[OrderObservation]:
    return [
        OrderObservation(
            session_id="lunch_001",
            observation_id="obs_tim_001",
            platform="doordash",
            zone="South Columbus",
            hotspot_name="Tim Hortons / Hamilton Rd",
            accepted=True,
            declined=False,
            offered_pay_total=6.80,
            offered_base_pay=2.30,
            offered_peak_pay=2.00,
            offered_tip_visible=2.50,
            peak_pay_active=True,
            offered_miles=2.2,
            actual_trip_miles=2.2,
            return_miles_estimate=0.8,
            zone_exit_miles=0.0,
            merchant_name="Tim Hortons",
            merchant_category="coffee",
            stack_count=1,
            merchant_wait_minutes=1.0,
            traffic_delay_minutes=1.0,
            parking_friction_minutes=0.0,
            delivery_handoff_minutes=1.0,
            was_hotspot_wait=False,
            hotspot_wait_minutes=0.0,
            acceptance_rate_pressure_seen=False,
            notes="High quality short run with peak pay.",
        ),
        OrderObservation(
            session_id="lunch_001",
            observation_id="obs_coffee_002",
            platform="doordash",
            zone="Blacklick / Eastland edge",
            hotspot_name="Main Ground Coffee",
            accepted=False,
            declined=True,
            offered_pay_total=7.30,
            offered_base_pay=2.30,
            offered_peak_pay=0.00,
            offered_tip_visible=5.00,
            peak_pay_active=False,
            offered_miles=5.4,
            actual_trip_miles=5.4,
            return_miles_estimate=1.5,
            zone_exit_miles=0.8,
            merchant_name="Main Ground Coffee",
            merchant_category="coffee",
            stack_count=1,
            merchant_wait_minutes=0.0,
            traffic_delay_minutes=0.0,
            parking_friction_minutes=0.0,
            delivery_handoff_minutes=0.0,
            was_hotspot_wait=False,
            hotspot_wait_minutes=0.0,
            acceptance_rate_pressure_seen=True,
            notes="Declined due to weak economic miles after return burden.",
        ),
        OrderObservation(
            session_id="lunch_001",
            observation_id="obs_kfc_003",
            platform="doordash",
            zone="Groveport",
            hotspot_name="KFC corridor",
            accepted=True,
            declined=False,
            offered_pay_total=9.80,
            offered_base_pay=2.80,
            offered_peak_pay=0.00,
            offered_tip_visible=7.00,
            peak_pay_active=False,
            offered_miles=7.0,
            actual_trip_miles=7.0,
            return_miles_estimate=0.0,
            zone_exit_miles=0.13,
            merchant_name="KFC",
            merchant_category="fast_food",
            stack_count=1,
            merchant_wait_minutes=3.0,
            traffic_delay_minutes=2.0,
            parking_friction_minutes=1.0,
            delivery_handoff_minutes=1.0,
            was_hotspot_wait=False,
            hotspot_wait_minutes=0.0,
            acceptance_rate_pressure_seen=False,
            notes="Accepted; decent payout with manageable burden.",
        ),
        OrderObservation(
            session_id="dinner_001",
            observation_id="obs_hurley_jj_004",
            platform="doordash",
            zone="Canal Winchester",
            hotspot_name="Jimmy John's / Gender Rd",
            accepted=True,
            declined=False,
            offered_pay_total=7.10,
            offered_base_pay=2.10,
            offered_peak_pay=0.00,
            offered_tip_visible=5.00,
            peak_pay_active=False,
            offered_miles=5.8,
            actual_trip_miles=5.8,
            return_miles_estimate=0.9,
            zone_exit_miles=0.4,
            merchant_name="Jimmy John's",
            merchant_category="sandwich",
            stack_count=1,
            merchant_wait_minutes=2.0,
            traffic_delay_minutes=1.0,
            parking_friction_minutes=1.0,
            delivery_handoff_minutes=1.0,
            was_hotspot_wait=False,
            hotspot_wait_minutes=0.0,
            acceptance_rate_pressure_seen=False,
            notes="Acceptable but not strong after burden added.",
        ),
    ]